# Generated by Django 5.1 on 2024-08-14 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_block_transaction_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='blockchain.election'),
        ),
    ]
